---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "FitNesse Eclipse"
keywords:    "FitNesse, fitnesse-editor, fitnesse-eclipse, fit, github, eclipse"
description: "Eclipse plugin for FitNesse"
source_link: "https://github.com/fitnesse-eclipse/fitnesse-eclipse"
favicon:     "img/fitnesse-eclipse.ico"
touch_icon:  "img/fitnesse-eclipse-touch.png"
google_analytics_key: UA-56774387-1
url: http://fitnesse-eclipse.github.io

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  
# collections
collections:
  releases:
    output: true